homepage:
  route: /
  method: GET
  target: JGLP\Controller\Index@index

check-elasticsearch:
  route: /check-elasticsearch
  method: GET
  target: JGLP\Controller\Check@elasticsearch

event:
  route: /event/[:event]?
  method: GET
  target: JGLP\Controller\Index@event